name: Build gallery

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    # Skip if the workflow was triggered by the bot itself
    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase onto latest main
        run: |
          git fetch origin main
          git checkout main
          git pull --rebase origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Generate gallery
        run: python Scripts/generate_gallery.py

      - name: Commit and push changes
        run: |
          if ! git diff --quiet; then
            git add docs/gallery
            git commit -m "chore(gallery): auto-generate thumbs and index.json [skip ci]"
            # rebase again in case main moved since job start
            git pull --rebase origin main || true
            git push origin main
          else
            echo "No changes to commit."
          fi
